FROM node:8-alpine

#RUN apk update && \
#    apk add --no-cache fish && \
#    rm -f /tmp/* /etc/apk/cache/*


#RUN npm install webpack -g
#RUN npm install node-sass-chokidar -g


WORKDIR /opt/suitedconnectors.poker/core/js
COPY ./core/js/yarn.lock ./core/js/package.json /opt/suitedconnectors.poker/core/js/

RUN yarn install

ENV PATH="/opt/suitedconnectors.poker/core/js/node_modules/.bin:${PATH}"