# Steps to set up a new docker-compose machine:
#
# docker-compose run django ./manage.py migrate
# docker-compose run django ./manage.py createsuperuser
# docker-compose up


version: '3'

volumes:
  node_modules:

services:
  nginx:
    image: nginx:alpine
    ports:
      - 80:80
      - 443:443
    links: 
      - "django"
    volumes:
      - ./etc/nginx/suitedconnectors-docker-compose.prod.conf:/etc/nginx/nginx.conf
      - ./data/certs:/opt/suitedconnectors.poker/data/certs
      - ./core:/opt/suitedconnectors.poker/core
      - ./data/static:/opt/suitedconnectors.poker/data/static

  postgres:
    image: postgres:13
    env_file:
      - ./env/beta-docker.env
      - .secrets-prod.env
    #ports:
    #  - 5432:5432
    expose:
      - 5432
    command: postgres -c shared_buffers=1GB
    volumes:
      - ./database/postgres:/var/lib/postgresql/data

  redis:
    image: redis:5-alpine
    entrypoint: redis-server --appendonly yes
    expose:
      - 6379
    volumes:
      - ./data/redis:/data

  django:
    build: .
    image: suitedconnectors:django_base
    hostname: suitedconnectors-prod
    working_dir: /opt/suitedconnectors.poker/core/
    command: daphne -b 0.0.0.0 -p 8000 suitedconnectors.asgi:channel_layer
    stdin_open: true
    tty: true
    depends_on: 
      - postgres
      - redis
    environment:
      SUITEDCONNECTORS_ENV: PROD
      POSTGRES_HOST: postgres
      REDIS_HOST: redis
      DJANGO_SETTINGS_MODULE: "suitedconnectors.settings"
      IS_DOCKER: 1
    env_file:
      - ./env/beta-docker.env
      - ./.secrets-prod.env
    expose: 
      - 8000
    volumes:
      - ./data:/opt/suitedconnectors.poker/data
      - ./core:/opt/suitedconnectors.poker/core
      - ./bin:/opt/suitedconnectors.poker/bin
      - ./env:/opt/suitedconnectors.poker/env

  worker:
    image: suitedconnectors:django_base
    working_dir: /opt/suitedconnectors.poker/core/
    entrypoint: /opt/suitedconnectors.poker/bin/worker-docker-entrypoint.sh
    user: root
    depends_on:
      - postgres
      - redis
    environment:
      SUITEDCONNECTORS_ENV: PROD
      POSTGRES_HOST: postgres
      REDIS_HOST: redis
      DJANGO_SETTINGS_MODULE: "suitedconnectors.settings"
      IS_DOCKER: 1
    env_file:
      - ./env/beta-docker.env
      - ./.secrets-prod.env
    volumes:
      - ./data:/opt/suitedconnectors.poker/data
      - ./data/logs:/var/log/supervisor
      - ./core:/opt/suitedconnectors.poker/core
      - ./bin:/opt/suitedconnectors.poker/bin
      - ./env:/opt/suitedconnectors.poker/env
      - ./etc/supervisor/suitedconnectors-docker-prod-worker.conf:/etc/supervisor/conf.d/supervisord.conf

  botbeat:
    image: suitedconnectors:django_base
    working_dir: /opt/suitedconnectors.poker/core/
    command: ./manage.py bot_heartbeat
    depends_on:
      - postgres
      - redis
    environment:
      SUITEDCONNECTORS_ENV: PROD
      POSTGRES_HOST: postgres
      REDIS_HOST: redis
      DJANGO_SETTINGS_MODULE: "suitedconnectors.settings"
      IS_DOCKER: 1
    restart: on-failure
    env_file:
      - ./env/beta-docker.env
      - ./.secrets-prod.env
    volumes:
      - ./data:/opt/suitedconnectors.poker/data
      - ./core:/opt/suitedconnectors.poker/core
      - ./bin:/opt/suitedconnectors.poker/bin
      - ./env:/opt/suitedconnectors.poker/env

  webpack:
    build:
      context: . 
      dockerfile: ./Dockerfile.webpack
    image: suitedconnectors:webpack
    command: sh -c "(webpack --mode development --watch --info-verbosity verbose & node-sass-chokidar --watch scss/ -o ../static/css 2>&1  &)| cat"
    stdin_open: true
    tty: true
    environment:
      SUITEDCONNECTORS_ENV: DEV
    volumes:
      - ./core/js:/opt/suitedconnectors.poker/core/js
      - ./core/static:/opt/suitedconnectors.poker/core/static
      # Hide local node_modules
      - ./core/js/node_modules:/src/node_modules
      # Add dumps for UI tests
      - ./core/dumps:/opt/suitedconnectors.poker/core/dumps


  dramatiq:
    image: suitedconnectors:django_base
    working_dir: /opt/suitedconnectors.poker/core/
    command: nice -15 ./manage.py rundramatiq --processes 1 --threads 1
    environment:
      SUITEDCONNECTORS_ENV: PROD
      POSTGRES_HOST: postgres
      REDIS_HOST: redis
    cap_add:
      - SYS_NICE
    depends_on: 
      - redis
      - postgres
    env_file:
      - ./env/beta-docker.env
      - ./.secrets-prod.env
    volumes:
      - ./data:/opt/suitedconnectors.poker/data
      - ./core:/opt/suitedconnectors.poker/core
      - ./bin:/opt/suitedconnectors.poker/bin
      - ./etc:/opt/suitedconnectors.poker/etc
 
  cloudflare:
    image: cloudflare/cloudflared
    network_mode: 'service:nginx'
    command: tunnel --no-autoupdate --hostname suitedconnectors-staging.zervice.io http://nginx
    depends_on:
      - django
    volumes:
      - ./data/certs/suitedconnectors.zervice.io.pem:/etc/cloudflared/cert.pem:ro

  yacron:
    image: suitedconnectors:django_base
    hostname: suitedconnectors-prod
    command: yacron -c /opt/suitedconnectors.poker/etc/yacron/suitedconnectors-prod-docker.yaml
    environment:
      SUITEDCONNECTORS_ENV: PROD
      POSTGRES_HOST: postgres
      REDIS_HOST: redis
      IS_DOCKER: 1
    depends_on: 
      - redis
      - postgres
    env_file:
      - ./env/beta-docker.env
      - ./.secrets-prod.env
    volumes:
      - ./etc:/opt/suitedconnectors.poker/etc
      - ./data:/opt/suitedconnectors.poker/data
      - ./core:/opt/suitedconnectors.poker/core
      - ./etc/yacron:/opt/suitedconnectors.poker/etc/yacron
      - ./bin:/opt/suitedconnectors.poker/bin
