version: 2
jobs:
  checkout_code:
    machine: true

    working_directory: ~/suitedconnectors

    steps:
      - restore_cache:
          keys:
            - suitedconnectors-repo
      - checkout
      - save_cache:
          key: suitedconnectors-repo
          paths:
            - ~/suitedconnectors
      - save_cache:
          key: suitedconnectors-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/suitedconnectors

  setupjs:
    docker:
      - image: circleci/python:3.7-node

    working_directory: ~/suitedconnectors

    steps:
      - restore_cache:
          keys:
            - suitedconnectors-repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          keys:
            - suitedconnectors-core-node_modules-v2@{{ checksum "core/js/package.json" }}

      
      - run: sudo apt install -yq fish; ./bin/suitedconnectors-ci setupjs | tee /tmp/setupjs.txt
      
      - save_cache:

          key: suitedconnectors-core-node_modules-v2@{{ checksum "core/js/package.json" }}

          paths:
            - core/js/node_modules

      - store_artifacts:
          path: /tmp/setupjs.txt

  lintjs:
    docker:
      - image: circleci/python:3.7-node

    working_directory: ~/suitedconnectors

    steps:
      - restore_cache:
          keys:
            - suitedconnectors-repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          keys:

            - suitedconnectors-core-node_modules-v2@{{ checksum "core/js/package.json" }}

      
      - run: sudo apt install -yq fish; ./bin/suitedconnectors-ci lintjs | tee /tmp/lintjs.txt

      - store_artifacts:
          path: /tmp/lintjs.txt
      
      - store_test_results:
          path: /tmp/reports

  testjs:
    docker:
      - image: circleci/python:3.7-node

    working_directory: ~/suitedconnectors

    steps:
      - restore_cache:
          keys:
            - suitedconnectors-repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          keys:
            - suitedconnectors-core-node_modules-v2@{{ checksum "core/js/package.json" }}

      
      - run: sudo apt install -yq fish; ./bin/suitedconnectors-ci testjs | tee /tmp/testjs.txt

      - store_artifacts:
          path: /tmp/testjs.txt

  compjs:
    docker:
      - image: circleci/python:3.7-node

    working_directory: ~/suitedconnectors

    steps:
      - restore_cache:
          keys:
            - suitedconnectors-repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          keys:
            - suitedconnectors-core-node_modules-v2@{{ checksum "core/js/package.json" }}
      
      - run: sudo apt install -yq fish; ./bin/suitedconnectors-ci compjsall | tee /tmp/compjs.txt

      - save_cache:
          key: suitedconnectors-staticfiles@{{ .Revision }}
          paths:
            - core/static/js/pages

      - store_artifacts:
          path: /tmp/compjs.txt

  setuppy:
    docker:
      - image: circleci/python:3.7

    working_directory: ~/suitedconnectors

    steps:
      - restore_cache:
          keys:
            - suitedconnectors-repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          keys:

            - suitedconnectors-core-venv-v1@{{ checksum "core/Pipfile" }}
      
      - run: sudo apt install -yq fish; ./bin/suitedconnectors-ci setuppy | tee /tmp/setuppy.txt
      
      - save_cache:
          key: suitedconnectors-core-venv-v1@{{ checksum "core/Pipfile" }}
          paths:
            - core/.venv

      - store_artifacts:
          path: /tmp/setuppy.txt

  lintpy:
    docker:
      - image: circleci/python:3.7

    working_directory: ~/suitedconnectors

    steps:
      - restore_cache:
          keys:
            - suitedconnectors-repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          keys:
            - suitedconnectors-core-venv-v1@{{ checksum "core/Pipfile" }}

      
      - run: sudo apt install -yq fish; ./bin/suitedconnectors-ci lintpy | tee /tmp/lintpy.txt

      - store_artifacts:
          path: /tmp/lintpy.txt
      
      - store_test_results:
          path: /tmp/reports

  testpy:
    docker:
      - image: circleci/python:3.7
      - image: circleci/postgres:12.1
        environment:
          POSTGRES_USER: suitedconnectors
          POSTGRES_DB: suitedconnectors
      - image: redis:4.0.6

    working_directory: ~/suitedconnectors

    steps:
      - restore_cache:
          keys:
            - suitedconnectors-repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          keys:
            - suitedconnectors-core-venv-v1@{{ checksum "core/Pipfile" }}
      
      - run: sudo apt install -yq fish; ./bin/suitedconnectors-ci testpy | tee /tmp/testpy.txt

      - store_artifacts:
          #path: ~/suitedconnectors/data/debug_dumps
          path: /tmp/testpy.txt

      - store_test_results:
          path: /tmp/reports

  integration_tests:
    docker:
      - image: circleci/python:3.7
      - image: circleci/postgres:12.1
        environment:
          POSTGRES_USER: suitedconnectors
          POSTGRES_DB: suitedconnectors
      - image: redis:4.0.6

    working_directory: ~/suitedconnectors

    steps:
      - restore_cache:
          keys:
            - suitedconnectors-repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          keys:
            - suitedconnectors-core-venv-v1@{{ checksum "core/Pipfile" }}
      
      - run: sudo apt install -yq fish; ./bin/suitedconnectors-ci integration_tests | tee /tmp/integration_tests.txt

      - store_artifacts:
          path: /tmp/integration_tests.txt

  screenshots:
    docker:
      - image: circleci/python:3.7-browsers
      - image: circleci/postgres:12.1
        environment:
          POSTGRES_USER: suitedconnectors
          POSTGRES_DB: suitedconnectors
      - image: redis:4.0.6

    working_directory: ~/suitedconnectors

    steps:
      - restore_cache:
          keys:
            - suitedconnectors-repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          keys:

            - suitedconnectors-core-venv-v1@{{ checksum "core/Pipfile" }}

      - restore_cache:
          keys:
            - suitedconnectors-staticfiles@{{ .Revision }}
      
      - run: sudo apt install -yq fish; ./bin/suitedconnectors-ci screenshots | tee /tmp/screenshots.txt

      - store_artifacts:
          path: /tmp/screenshots
      
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - checkout_code
      - setupjs:
          requires:
            - checkout_code
      - lintjs:
          requires:
            - setupjs
      - testjs:
          requires:
            - setupjs
      - compjs:
          requires:
            - lintjs
            - testjs

      - setuppy:
          requires:
            - checkout_code
      - lintpy:
          requires:
            - setuppy
      - testpy:
          requires:
            - setuppy

      - integration_tests:
          requires:
            - lintpy
            - testpy

      - screenshots:
          requires:
            - lintpy
            - compjs

