# Generated by Django 2.2.11 on 2023-02-17 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0040_auto_20201222_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokertable',
            name='table_type',
            field=models.CharField(choices=[('NLHE', "No Limit Hold 'em"), ('PLO', 'Pot Limit Omaha'), ('FPLO', 'Five Card Pot Limit Omaha'), ('BNTY', 'No Limit Bounty'), ('IRNLHE', 'No Limit Irish'),('SDNLHE', "Short Deck No Limit Hold 'em"), ('SDPLO', 'Short Deck No Limit Bounty')], default='NLHE', max_length=10),
        ),
        migrations.AlterField(
            model_name='pokertournament',
            name='game_variant',
            field=models.CharField(choices=[('NLHE', "No Limit Hold 'em"), ('PLO', 'Pot Limit Omaha'), ('FPLO', 'Five Card Pot Limit Omaha'), ('BNTY', 'No Limit Bounty'), ('IRNLHE', 'No Limit Irish'), ('SDNLHE', "Short Deck No Limit Hold 'em"), ('SDPLO', 'Short Deck No Limit Bounty')], default='NLHE', max_length=10),
        ),
    ]
