# Generated by Django 2.2.11 on 2023-02-19 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0042_auto_20230217_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokertable',
            name='table_type',
            field=models.CharField(choices=[('NLHE', "No Limit Hold 'em"), ('PLO', 'Pot Limit Omaha'), ('BNTY', 'No Limit Bounty'), ('FPLO', 'Five Card Pot Limit Omaha'), ('SDNLHE', "Short Deck No Limit Hold 'em"), ('SDPLO', 'Short Deck Pot Limit Omaha')], default='NLHE', max_length=10),
        ),
        migrations.AlterField(
            model_name='pokertournament',
            name='game_variant',
            field=models.CharField(choices=[('NLHE', "No Limit Hold 'em"), ('PLO', 'Pot Limit Omaha'), ('BNTY', 'No Limit Bounty'), ('FPLO', 'Five Card Pot Limit Omaha'), ('SDNLHE', "Short Deck No Limit Hold 'em"), ('SDPLO', 'Short Deck Pot Limit Omaha')], default='NLHE', max_length=10),
        ),
    ]
