# Generated by Django 2.2.11 on 2023-02-23 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0043_auto_20230219_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokertable',
            name='precision',
            field=models.IntegerField(default=2),
        ),
    ]
