# Generated by Django 2.2.11 on 2023-03-04 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0045_auto_20230303_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokertable',
            name='table_type',
            field=models.CharField(choices=[('NLHE', "No Limit Hold 'em"), ('PLO', 'Pot Limit Omaha'), ('BNTY', 'No Limit Bounty'), ('FPLO', 'Five Card Pot Limit Omaha'), ('SDNLHE', "Short Deck No Limit Hold 'em"), ('SDPLO', 'Short Deck Pot Limit Omaha'), ('IRNLHE', 'No Limit Irish')], default='NLHE', max_length=10),
        ),
        migrations.AlterField(
            model_name='pokertournament',
            name='game_variant',
            field=models.CharField(choices=[('NLHE', "No Limit Hold 'em"), ('PLO', 'Pot Limit Omaha'), ('BNTY', 'No Limit Bounty'), ('FPLO', 'Five Card Pot Limit Omaha'), ('SDNLHE', "Short Deck No Limit Hold 'em"), ('SDPLO', 'Short Deck Pot Limit Omaha'), ('IRNLHE', 'No Limit Irish')], default='NLHE', max_length=10),
        ),
    ]
