# Generated by Django 2.0.8 on 2018-09-26 08:39

from django.db import migrations
import suitedconnectors.models


class Migration(migrations.Migration):

    dependencies = [
        ('suitedconnectors', '0023_user_light_theme'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', suitedconnectors.models.CaseInsensitiveUserManager()),
            ],
        ),
    ]
